version: '3.8'

services:
  huggingface-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    ports:
      - "8080:80"
    volumes:
      - ./data/huggingface-cache:/data
    environment:
      - MODEL_ID=sentence-transformers/all-MiniLM-L6-v2
    restart: unless-stopped

  ifttt-twitter-webhook:
    image: ghcr.io/phuihock/ifttt-twitter-webhook:main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - DEBUG=${DEBUG:-False}
      - PORT=${PORT:-5000}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-False}
      - CHROMA_TELEMETRY=${CHROMA_TELEMETRY:-False}
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - HF_WAIT_FOR=${HF_WAIT_FOR:-1}
    restart: unless-stopped
    depends_on:
      huggingface-embeddings:
        condition: service_started
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
