version: '3.8'

services:
  iftttwh:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - WEBHOOK_SECRET=your_secret_key_here
      - PORT=5000
      - DEBUG=false
    restart: unless-stopped